development:
  bucket: LearnTo-dev
  access_key_id: ENV["S3_KEY"] 
  secret_access_key: ENV["S3_SECRET"]
test:
  bucket: LearnTo-test
  access_key_id: ENV["S3_KEY"]
  secret_access_key: ENV["S3_SECRET"]
production:
  bucket: LearnTo-production
  access_key_id: ENV["S3_KEY"]
  secret_access_key: ENV["S3_SECRET"]
